# --- Conexión a la Base de Datos ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/motor_inversiones}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Pool de Conexiones ---
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=90000
spring.datasource.hikari.max-lifetime=600000

# --- Configuración de Hibernate/JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# --- Configuración de Red ---
server.port=${PORT:8080}